language: cpp
compiler:
 - gcc
 - clang
branches:
 only:
  - master
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libqt4-dev zlib1g-dev qt4-dev-tools libqtwebkit-dev xvfb xauth
script: mkdir _build && cd _build && qmake CONFIG+=debug PREFIX=/usr ../trojita.pro && make && xvfb-run -a make test && sudo make install
notifications:
 irc: "chat.freenode.net#trojita"
